### ISSUE TITLE
The style selector only is shown when the manual is compiled with the "mathjax" option

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#1]
[The following was originally reported August 1st, 2013]

GAPDoc embeds a style switcher on HTML pages it generates. However, due to a bug, this switcher is only shown when the documentation was built with the "mathjax" option on. The problem is caused by this code in `manual.js`, which is responsible for inserting the style switcher:
```js
/* this adds a "[Style]" link next to the MathJax switcher   */
function addStyleLink() {
  var line = document.getElementById("mathjaxlink");  // <--- bug is here
  var el = document.createElement("a");
  var oncl = document.createAttribute("href");
```

One simple solution for this would be to always insert an (invisible) anchor element in the HTML code next to where the "mathjaxlink" appears, and then change the JavaScript code above to hook into that. So you could change this HTML
```
 <p id="mathjaxlink" class="pcenter"><a href="chap0_mj.html">[MathJax on]</a></p>
```
to something like this:
```
  <div id="extralinks" class="pcenter"><a href="chap0_mj.html">[MathJax on]</a></div>
```
but now you'd always insert the `extralinks` div, i.e. if "MathJax" is disabled, there would still be this code insert:
```
  <div id="extralinks" class="pcenter"></div>
```
The corresponding change to the JavaScript code should be clear.

**Comment by frankluebeck** [comment]
Yes, this makes sense. This works now.

**Comment by fingolfin** [comment]
Not sure what you mean with "This works now." -- that you have a fix locally and will eventually push it to this repository and/or make a release with it?
