### ISSUE TITLE
MakeGAPDocDoc does not create a manual.six when no pdflatex is present

### ISSUE THREAD

**Issue by sebasguts** [frankluebeck/GAPDoc#10]
While there might be information missing in the `manual.six`, it might be worth thinking about creating it. Otherwise there is no help in the `GAP` session.
This is interesting for Docker images, where probably undeposited packages are added via `git clone`, and the manual needs to be build in the image.

**Comment by frankluebeck** [comment]
A proper build of a manual should contain the pdf-version. Without it the page numbers of sections are not known and so the information needed in the `manual.six` file is not complete. 

I don't want to support incomplete builds of  manuals (and incomplete `manual.six` files).

**Comment by ChrisJefferson** [comment]
Installing pdflatex can be a big install -- on Macs the standard way to install is mactex, which is 2.8GB. That is a big requirement for users who don't care about PDF manuals (I never look at them myself).

**Comment by alex-konovalov** [comment]
@frankluebeck do I understand this correctly that there is no way to build only an HTML version of the manual any more? I remember that it was there in the past, and I've enjoyed it while developing my package on Windows PC without latex. I have a question from a package author who uses Windows, and would like to advise similar setup (she is able to login to Linux to make a proper release, but her everyday development environment is Windows, so being able just to check that the XML code can be parsed correctly and look at the HTML version of the manual will be great).

**Comment by sebasguts** [comment]
@alex-konovalov No, the HTML version is produced correctly. Just not the `manual.six` file, which seems to be needed for the inline help from the GAP-Session.

**Comment by frankluebeck** [comment]
@ChrisJefferson: For reading (and maybe printing) complete sections of a manual I would still consider the pdf-version as important. And it is also the best version to read sections with a lot of mathematical content (although nowadays MathJax does a good job for this as well).

Therefore, as mentioned above, I would not like to change the setup such that it becomes easy to produce manuals without the pdf-version. Most users of GAP will have pdflatex available anyway. (And it is not so difficult to hack around this restriction if you really want.)

**Comment by frankluebeck** [comment]
I have now built in a hook. If you set
```
GAPInfo.SIXFILEIGNOREMISSINGPNR := true;
```
a `manual.six` file should be generated with all page numbers set to `-1`.
But for the reasons mentioned above this will not be documented.

**Comment by sebasguts** [comment]
Thank you, this is a good solution.
