### ISSUE TITLE
Add test files

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#11]
There are no test files in the GAPDoc package. 

Of course, it is exercised regularly when we build GAP manuals in nightly/weekly tests, and by those who use GAP documentation while working with GAP. However, this is not automated (even in CI tests, we check that manuals are built, but we don't look inside them) , and it's not clear how much code coverage this provides. 

Therefore, establishing a proper set of test files would be beneficial.

**Comment by frankluebeck** [comment]
The test consists in this case of the 3 manuals coming with GAPDoc. In particular, all types of elements occur in the "GAPDoc example" manual.

**Comment by alex-konovalov** [comment]
Thanks. The it seems that as a first step, we can put `makedocrel.g` or a file derived from it as default test in `PackageInfo.g` - it will rebuild GAPDoc manuals during the test, but those will never be redistributed. And it's definitely appropriate to try to build GAPDoc manuals in Travis and then use CodeCov...

**Comment by alex-konovalov** [comment]
That may be interesting - I've run 
```
gapdev -r -A --cover output.gz makedocrel.g 
```
and then in GAP
```
LoadPackage("profiling");
OutputAnnotatedCodeCoverageFiles("output.gz");
```
Attached is part of the output which shows how much GAPDoc is exercised by `makedocrel.g`. I hope we exercise `lib/Examples.gi` in our regression tests well, so that's only zero coverage in the `makedocrel.g`, but not so sure about other files with less than 60% coverage.



![screen shot 2017-02-20 at 23 02 41](https://cloud.githubusercontent.com/assets/5751387/23144685/3af284b6-f7c1-11e6-8839-8d1088e21f22.png)

**Comment by frankluebeck** [comment]
Thanks for this. So, the coverage is actually pretty good. The BibTeX tools are tested a lot within the Browse package which provides access to the GAP bibliography. The "examples" code is used with the manual tests of the main manuals and many package manuals.

I don't think I want to spend time on producing a lot of bad input for many functions just to cover their error messages.
