### ISSUE TITLE
UTF8 functions are slow

### ISSUE THREAD

**Issue by ChrisJefferson** [frankluebeck/GAPDoc#15]
Profiling GAPDoc, over half the runtime seems to be spent in the functions which translate to and from UTF8.

I am happy to rewrite these in C, the only question is where to put them. In a kernel extension in GAPDoc, in GAP core (suitably documented), or in a new Unicode package?

**Comment by frankluebeck** [comment]
In my experience the run time for producing manuals is much dominated by the calls to `pdflatex`. 

I a few profiling tests I could not confirm that so much time is spent in such translations.
Of course, it would not hurt to have fast kernel functions of `UNICODE_RECODE.Decoder.("UTF-8")`
and `UNICODE_RECODE.Encoder.("UTF-8")` available. (Are these the functions you were talking about?) But it is not really needed for GAPDoc,  and it would not be worth the effort if it made the installation of GAPDoc more difficult.
