### ISSUE TITLE
cdn.mathjax is closing down

### ISSUE THREAD

**Issue by ChrisJefferson** [frankluebeck/GAPDoc#17]
GAPDoc is currently hard-wired to access:

``"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"``

This is being closed down, in a month!

They suggest switching to: ``https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML``

**Comment by ChrisJefferson** [comment]
Looked at this more deeply, there are many GAP packages which are hit by this problem.

I think we need to:

1) Make a new release of GAPDoc ASAP (within a week if possible), so people then have time to make new releases of packages, and then release a new GAP.

2) I wonder if we should prepare to make a gap release where we manually edit the documentation of all packages, so it at least continues to work?

**Comment by ChrisJefferson** [comment]
Further suggestion: We could also put a copy of mathjax on gap-system.org , so in future we do not rely on other people.

**Comment by dimpase** [comment]
My understanding is that cloudflare (a sponsor of cdnjs, which provides the recommended alternative MathJax CDN hosting) might cause problems for people behind tricky firewalls.

By the way, https://www.mathjax.org/cdn-shutting-down/ (updated 10/4/17) says they will provide a temporary redirect to cdnjs, so this not as urgent...

**Comment by frankluebeck** [comment]
Thanks for the hint! After discussions on the mailing list, I have now changed the URL to the one suggested on the MathJax site.
