### ISSUE TITLE
Problem documenting `\[\]` methods in mathjax mode

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#2]
[Originally reported October 24, 2014]

Trying to document a method for `\[\]` is broken when MathJax is active, as that treats that as an attempt to enable the LaTeX display math mode. For an example of the resulting breakage, look here:
  http://www.gap-system.org/Manuals/doc/ref/chap21_mj.html#X7B202D147A5C2884

One workaround would be to detect this case in GAPDoc, and emit code which prevents MathJax from treating the text as a may display mode limiter.

Another way to fix this would be change the MathJax configuration, to turn of parsing of `\[...\]` completely, and use another sequence to activate math mode, resp. to explicitly activate mathmode for sequences that need it -- since GAPDoc generates the relevant HTML anyway, that shouldn't be too hard to pull off.

**Comment by fingolfin** [comment]
This is supposedly fixed in 40d7cb699252f7c6ec1801d79989b53befc3e213 -- but without a release, the documentation on the GAP website will of course stay broken. Thus I thought it best to report it anyway, to support my request for a release of GAPDoc. This is not fixed until the fix is made available to users, after all.

**Comment by fingolfin** [comment]
Also, it is not documented in the CHANGES file, it seems?

**Comment by frankluebeck** [comment]
Yes, this problem was fixed by 40d7cb6. Typesetting such special function names within headers in &lt;code> tags looks nicer anyway, and it avoids the misinterpretation by MathJax.

I prefer to use the default configuration of MathJax.

This is not mentioned in the CHANGES file because this is just a minor typographical change.

**Comment by fingolfin** [comment]
I don't agree that missing resp. invisible text is just a "minor" typographical issue.
