### ISSUE TITLE
Bad error message from ManSection

### ISSUE THREAD

**Issue by ChrisJefferson** [frankluebeck/GAPDoc#20]
I made a `ManSection` with no `Func`, `Var`, etc. This produces the following unhelpful error:

```
#I First run, collecting cross references, index, toc, bib and so on . . .
Error, List Element: <list>[2] must have an assigned value in
  while not r.content[i].name in funclike  do
    i := i + 1;
od; at /Users/caj/reps/gap/gap/pkg/GAPDoc-1.5.1/lib/GAPDoc2Text.gi:1605 called from
GAPDoc2TextProcs.(r.name)( r, str ); at /Users/caj/reps/gap/gap/pkg/GAPDoc-1.5.1/lib/GAPDoc2Text.gi:380 called from
...
```

The documentation suggests I can use a `Label` instead of a `Func`,etc. But I couldn't get that to work. For now I have just put a fake `Var` in.

**Comment by frankluebeck** [comment]
I'm not sure what you want to achieve here. The `<ManSection>` elements are meant for documenting a function or variable.  

May you just want to use a `<Subsection>` (which can and probably should have a `Label` attriibute for referencing purposes)?

**Comment by ChrisJefferson** [comment]
That wasn't clear to next I thought mansection was just for manual section. Whichever fix, the error message should probably be better?

**Comment by frankluebeck** [comment]
It is now checked in `CheckAndCleanGapDocTree` if a `ManSection` contains one of the elements which must be there. (This cannot be specified in the DTD but is documented.)
This check allows to generate a more useful error message.
