### ISSUE TITLE
Provide `Constructor` ManItem

### ISSUE THREAD

**Issue by sebasguts** [frankluebeck/GAPDoc#23]
Currently there is no `Constructor` ManItem, to document constructors. Since the filters given for a constructor behave differently as for operation, it would be good to be able to indicate that something is a constructor.

**Comment by frankluebeck** [comment]
This sounds sensible.
The commit ["Added <Constr> elements to document constructors." ](https://github.com/frankluebeck/GAPDoc/commit/954e0bb5c7ef2b0a336e44d6d16fb690b1a31666) provides a new element `<Constr>`.
