### ISSUE TITLE
Reference to "GAPDocExample" in chapter 3 of the GAPDoc manual

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#24]
Chapter 3 of the GAPDoc manual contains this sentence near the start: "Instead we provide an extra document with book name GAPDocExample (also accessible from the GAP online help)."

This is not so easy to find for a user. For starters, one might try this to find it:
```
gap> ??GAPDocExample
Help: no matching entry found
```
If one knows how to list books, one may discover that it actually can be found under the name "GAPDoc Example", possibly leading to a session like this:
```
gap> ?GAPDoc Example
Help: no matching entry found
Help: Are you looking for a certain book? (Trying '?GAPDoc Example:' ...
gap> ?GAPDoc Example:
...
```
Perhaps the sentence could be augmented to say something like, "It can for example be accessed by typing `?GAPDoc Example:` into a GAP session."

In the HTML version, e.g. at <https://www.gap-system.org/Manuals/pkg/GAPDoc-1.5.1/doc/chap3.html> this isn't an option, though. For this, it would be nice if there was an actual hyperlink to `../example/chap0.html` resp. https://www.gap-system.org/Manuals/pkg/GAPDoc-1.5.1/example/chap0.html

**Comment by frankluebeck** [comment]
This is mainly a typo. The book is called `GAPDoc Example`. 

But I have slightly changed the text and included a link to the other book, as suggested.
