### ISSUE TITLE
Migration from a4wide to geometry package

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#25]
The a4wide package (https://ctan.org/pkg/a4) is deprecated, and may not be installed by default. For example, this happens on our new Linux machine:
```
#I Writing LaTeX file, 4 x pdflatex with bibtex and makeindex, 
#W There were LaTeX errors:
! LaTeX Error: File `a4wide.sty' not found.

Type X to quit or <RETURN> to proceed,
____________________
! Emergency stop.
<read *> 
         
____________________
!  ==> Fatal error occurred, no output PDF file produced!
____________________
```
It is suggested to switch to the geometry package (https://ctan.org/pkg/geometry).

**Comment by frankluebeck** [comment]
Sounds sensible to remove the dependency on `a4wide`. I have substituted it by using the  `geometry` package with parameters that produce almost the same output as before  (commit 318a60f3327650ee830f).
