### ISSUE TITLE
SearchMR does not work

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#26]
Apparently some changes in MathSciNet caused this:
```
gap> ll := SearchMR(rec(Author:="Gauss", Title:="Disquisitiones"));
[  ]
```

**Comment by fingolfin** [comment]
Adding HTTPS support to `io` makes no sense in my eyes; it would require lots of dependencies to building `io`, and really is way off the core missing of the `io` package.

So I think calling wget and/or curl (note that the latter is always available on OS X, but not the former) or using a package wrapping e.g. `libcurl` (such as <https://github.com/gap-packages/curlInterface>) will be the long-term solution.

**Comment by frankluebeck** [comment]
Ok, I have reenabled `SearchMR` using a simple utility function `GetByWgetOrCurl` (6108fcb) which does what the name says.

**Comment by alex-konovalov** [comment]
@frankluebeck excellent, thanks! I am eager to try this.

**Comment by alex-konovalov** [comment]
@frankluebeck thanks a lot - picked up 471 new GAP citation from MathSciNet (this has not been run for a while)!
