### ISSUE TITLE
Using type="html" in SearchMR

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#31]
The documentation for `SearchMR` says
```
##  Furthermore, the component <C>type</C> can be specified. It can be one of 
##  <C>"bibtex"</C> (the default if not given), <C>"pdf"</C>, <C>"html"</C> and
##  probably others. In the last  cases the function returns a string with
##  the correspondig PDF-file or web page from <Package>MathSciNet</Package>.
```
However, with `type="html"` it returns an empty list. It seems to me that one should put lines
```
 if r.type <> "bibtex" then
    return res;
  fi;
```
into
```
  # get all entries
  Append(uri, "&extend=1");
  uri := Concatenation("https://",SEARCHMRHOST,uri);
  res := GetByWgetOrCurl(uri);
  if r.type <> "bibtex" then
    return res;
  fi;
  i := PositionSublist(res, "<pre>\n@");
  extr := [];
  while i <> fail do
    Add(extr, res{[i+5..PositionSublist(res, "</pre>", i)-1]});
    i := PositionSublist(res, "<pre>\n@", i);
  od;
```
so that it returns `res` without any further processing in the last cases. I have this change locally, and I can submit a PR.

**Comment by frankluebeck** [comment]
I have introduced the proposed change. But since this functionality doesn't look too useful, I have also introduced a `uri := true` option. If given the URI is returned as a string and not the result of its call.
This is probably useful, if `type` is not `bibtex`.
