### ISSUE TITLE
ASCII encoding is broken

### ISSUE THREAD

**Issue by RussWoodroofe** [frankluebeck/GAPDoc#35]
Setting GAPInfo.TermEncoding to "ASCII" breaks most display functions in GAP.

The following sample input/output gives a good example of the problem:
gap> GAPInfo.TermEncoding:="ASCII";
Error, Record: '<rec>.XML' must have an assigned value in
  return UNICODE_RECODE.TABLES.(nam){List( str, INT_CHAR ) + 1}
 ; at /Applications/Gap.app/Contents/gap/pkg/GAPDoc-1.6.1/lib/UnicodeTools.gi:\
59 called from 
UNICODE_RECODE.Decoder.(enc)( str 
 ) at /Applications/Gap.app/Contents/gap/pkg/GAPDoc-1.6.1/lib/UnicodeTools.gi:\
575 called from
Unicode( s, GAPInfo.TermEncoding 
 ) at /Applications/Gap.app/Contents/gap/pkg/GAPDoc-1.6.1/lib/UnicodeTools.gi:\
1227 called from
SHELL( GetBottomLVars(  ), false, false, 3, true, prompt, function (  )
      if IsBound( OnGAPPromptHook ) and IsFunction( OnGAPPromptHook ) then
          OnGAPPromptHook(  );
      else
          return;
      fi;
      return;
  end, "*stdin*", "*stdout*", true 
 ); at /Applications/Gap.app/Contents/gap/lib/session.g:60 called from
<function "SESSION">( <arguments> )
 called from read-eval loop at *stdin*:8
you can 'return;' after assigning a value
brk> 

(Tested also from Terminal.app, with similar results.)

My best guess is that the problem arises because ASCII gets remapped to "ANSI_X3.4-1968", and that the dot is somehow causing the problem.  I'm not sure of the best fix, which is why I'm submitting an Issue rather than a PR.

**Comment by frankluebeck** [comment]
@RussWoodroofe: this was fixed in commit 5dadd8b92c23d09cccd32f4 and will be in the next release I'm just preparing.
