### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#41]
It would be really useful to be able to use the new `nopdf` feature easily -- in particular for CI tests, as it means that one does not have to provide a full pdflatex installation, just to test building the documentation. 

The sooner there is a release, the sooner I can ask people to install GAPDoc 1.6.3, and it'll be in the next GAP release, too.

**Comment by frankluebeck** [comment]
Released GAPDoc 1.6.3
