### ISSUE TITLE
Error with umlauts in names if LANG is unset

### ISSUE THREAD

**Issue by zickgraf** [frankluebeck/GAPDoc#43]
If I unset the `LANG` environment variable and apply
```
StringBibXMLEntry(ParseBibXMLextString(BibEntry(pkg)).entries[1],"HTML")
```
to a `pkg` with authors having an "ü" in their last name, I get the following error:
```
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `in' on 2 arguments
The 2nd argument is 'fail' which might point to an earlier problem
 at /usr/lib/gap/lib/methsel2.g:249 called from
UChar( ' ' ) in str at .gap/pkg/GAPDoc/lib/BibXMLextTools.gi:1138 called from
letters( a[1], true ) at .gap/pkg/GAPDoc/lib/BibXMLextTools.gi:1191 called from
BuildRecBibXMLEntry( entry, entry, type, strings, opts ) at .gap/pkg/GAPDoc/lib/BibXMLextTools.gi:1635 called from
CallFuncList( RecBibXMLEntry, arg ) at .gap/pkg/GAPDoc/lib/BibXMLextTools.gi:1726 called from
StringBibXMLEntry( ParseBibXMLextString( BibEntry( pkg ) ).entries[1], "HTML" ) at update.g:181 called from
...  at update.g:195
```
I came across this while executing the `update.g` script of [GitHubPagesForGAP](https://github.com/gap-system/GitHubPagesForGAP) in a CI environment, where `LANG` is not set.

Is this a bug, or expected/intended behaviour?

cc @mohamed-barakat

**Comment by frankluebeck** [comment]
Thanks for this report. I don't think that this is an error in GAPDoc, but in the GAP library.

The problem should be resolved by [this commit](https://github.com/gap-system/gap/commit/ca6a3010d1387cc5c04de5f2a7a38a0e5374a7dc) in the GAP library.

**Comment by zickgraf** [comment]
I can confirm that the issue does not occur anymore with gap-master. Thanks a lot for the fix!
