### ISSUE TITLE
Move GAPDocManualLab and GAPDocManualLabFromSixFile from GAP to GAPDoc, and possibly document them

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#5]
The commands `GAPDocManualLab` and `GAPDocManualLabFromSixFile` are used by various packages when generating their manuals. It seems (but I might be wrong here?) that they are there to allow package manuals written using gapdocmacro to reference documentation in packages using GAPDoc?

If that's correct, perhaps most packages using `GAPDocManualLab` and `GAPDocManualLabFromSixFile` could stop using them? 

If it's wrong, and there is still a need to call these, perhaps they should be documented?

Also, I am confused as to why they are in GAP, and not in GAPDoc -- GAPDoc even appears in their name, and they seem to serve no purpose if one uses another documentation system?

**Comment by frankluebeck** [comment]
The documented function `GAPDocManualLab`  is needed when old `gapmacro.tex` manuals want to refer to GAPDoc style manuals. So, one could as well argue that this is a utility belonging to `gapmacro.tex` which is the reason why it is in the library.

**Comment by fingolfin** [comment]
`GAPDocManualLab` is not in the GAP reference manual nor help system, so I'd consider it undocumented. Though I now see that `package.gd` contains a documentation comment for it, so perhaps it was meant to be documented, and this was just forgotten?

**Comment by frankluebeck** [comment]
Try:
`?GAPDocManualLab`

**Comment by alex-konovalov** [comment]
It's mentioned in one line of the guidance from the Example package and has an index entry there (the guidance that we indent to migrate to the GAP reference manual, but not completed yet in https://github.com/gap-system/gap/pull/484).

If it's used, I suggest to hook the ManSection from [package.gd](https://github.com/gap-system/gap/blob/aad9cb036fcd650b844fe3e16f3c4f06855f40f9/lib/package.gd) to the GAP reference manual.

**Comment by frankluebeck** [comment]
> If it's used, I suggest to hook the ManSection from package.gd to the GAP reference manual.

Yes, probably somewhere in the Chapter "84 Interface to the GAP Help System"

**Comment by alex-konovalov** [comment]
We have revised the chapter with the guidance for package authors, and it does not mention `gapmacro.tex` any more. Hence I think there no need to hook the ManSection on `GAPDocManualLab` from package.gd to the GAP reference manual either.
