### ISSUE TITLE
Is there a way to reference the title page in a GAPDoc manual?

### ISSUE THREAD

**Issue by wilfwilson** [frankluebeck/GAPDoc#51]
I know how to reference chapters within a manual, i.e. `<Ref Chap="LABEL"/>`. The title page usually occurs as the first "chapter" in a manual, and once or twice I have thought it might be nice to be able to directly refer the user to the title page (eg.: "For more information about this, please contact the author, whose contact details are given on the title page.").

Is there a way to do this, and if not, please could you please add such a way - perhaps as `<Ref TitlePage/>`?

(I have tried for instance `<Ref Chap="TitlePage"/>`, but that doesn't work).

**Comment by frankluebeck** [comment]
GAPDoc produces for all its manuals search entries "Title page", and similarly "Bibliography" and "Index". So, you can refer to them as in:
```
see the page  <Ref BookName="GAPDoc" Label="title page"/>.
```
which will look like:

see the page [GAPDoc: Title page](https://www.gap-system.org/Manuals/pkg/GAPDoc/doc/chap0_mj.html#X7D2C85EC87DD46E5)

Within the same manual you can link to its title page as you can link to any place. Use the `<Label>` element as in the following example:

```
<Title><Label Name="TitleLabel"/>
Title of this manual </Title>
```

and later link to it as in:

```
see the  <Ref Label="TitleLabel" Text="title page"/> of this manual.
```

**Comment by wilfwilson** [comment]
Thank you for these explanations, it's good to know.
