### ISSUE TITLE
Whitespace under tables in HTML output

### ISSUE THREAD

**Issue by wilfwilson** [frankluebeck/GAPDoc#52]
I have noticed that extra whitespace is added underneath tables in the HTML versions of GAPDoc manuals. Is this deliberate or accidental? If it is accidental, I request that it be removed, or at least reduced.

Consider the following GAPDoc chapter containing just a table and some surrounding text:
```xml
<Chapter Label="A table">
  <Heading>Some heading</Heading>

  First item of text.

  <Table Align="ll">
    <Row>
      <Item><B>Column</B></Item>
      <Item><B>Data</B></Item>
    </Row>
    <HorLine/>
    <Row>
      <Item>
        Nonsense
      </Item>
      <Item>
        More nonsense
      </Item>
    </Row>
    <Row>
      <Item>
        Nonsense
      </Item>
      <Item>
        More nonsense
      </Item>
    </Row>
  </Table>

  Second item of text.

</Chapter>
```
This chapter is rendered as follows in the PDF **[Screenshot]**:
> <img width="453" alt="pdf-output" src="https://user-images.githubusercontent.com/8956868/151787491-c498b92a-a1cd-4def-ae9c-c335f4fef976.png">

However, in the HTML version, there is significantly more whitespace underneath the table, before the line "Second item of text" **[Screenshot]**:
> <img width="407" alt="html-output" src="https://user-images.githubusercontent.com/8956868/151787488-76bf5990-ec9d-4b86-9ea7-feb151de1334.png">

I would prefer the extra whitespace to be removed. Here is the HTML part of the chapter, where we can see that the additional whitespace is coming from the code `<br /><p>&nbsp;</p><br />`:
```html
<p>First item of text.</p>

<div class="pcenter"><table class="GAPDocTable">
<tr>
<td class="tdleft"><strong class="button">Column</strong></td>
<td class="tdleft"><strong class="button">Data</strong></td>
</tr>
<tr>
<td class="tdleft">Nonsense</td>
<td class="tdleft">More nonsense</td>
</tr>
<tr>
<td class="tdleft">Nonsense</td>
<td class="tdleft">More nonsense</td>
</tr>
</table><br /><p>&nbsp;</p><br />
</div>

<p>Second item of text.</p>
```

**Comment by frankluebeck** [comment]
Thanks for the clear description and analysis.

This empty paragraph was appended to a table in the HTML version from the beginning of GAPDoc. I don't remember why I had added it.

It is now removed (e71363b).

**Comment by wilfwilson** [comment]
Thank you.
