### ISSUE TITLE
MathJax problem

### ISSUE THREAD

**Issue by ThomasBreuer** [frankluebeck/GAPDoc#53]
Cross-references from a package manual to the documentation of operations like `\[\]` and `\[\]:=` in the GAP Reference Manual are turned into HTML code that looks as follows.
```
<code class="func">\[\]</code> (<a href="..."><span class="RefLink">Reference: \[\]</span></a>)
```
With MathJax, the first `\[\]` is rendered correctly but the second `\[\]` is apparently interpreted as an (empty) displayed formula.

This problem has been observed in the JuliaInterface manual, see oscar-system/GAP.jl/issues/786.

**Comment by frankluebeck** [comment]
Thanks for this example. This should be fixed now in the dev-version of GAPDoc (commit 49d76a7c5bb3020d41db5166b30a1c0c6bc59b0c).
