### ISSUE TITLE
ExtraPreamble is undocumented

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#6]
[Originally reported April 15, 2014]

The documentation of `SetGapDocLanguage` says "[...] see the information on ExtraPreamble in GAPDoc2LaTeX.". However, neither there nor anywhere else is any documentation for `ExtraPreamble`.

**Comment by frankluebeck** [comment]
Good spot. The reference is now to `GAPDoc: SetGapDocLaTeXOptions`.
