### ISSUE TITLE
<C> fails to protect `--` when generating TeX/PDF output?

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#63]
The GAPDOc manual says regarding `<C>`:
> This element is used to mark something as a piece of code like for example a GAP expression. It is guaranteed that the converters typeset this exactly as in the Listing element

However, the manual for `nq` contains this fragment:
```
In order for the <F>configure</F> script to find your copy of GMP, you
may have tell it where to find it via <C>--with-gmp=PATH</C>, where
<Q>PATH</Q> is the path where GMP was installed:

<Listing Type="Installation"> ./configure --with-gmp=PATH </Listing>
If necessary, you may combine <C>--with-gmp</C> and
<C>--with-gaproot</C>.
```
Note that `--with-gmp` occurs twice inside a `<C>` and once in a `<Listing>`. Based on my reading of the GAPDoc manual, I would expect these to be typeset exactly the same way. But unfortunately they are not:

<img width="802" alt="Screenshot 2023-01-23 at 21 57 01" src="https://user-images.githubusercontent.com/241512/214148319-b96d2ace-2e21-405d-8383-9a5f1219388f.png">

Note how `--` is rendered as a simple dash inside the `<C>`.

**Comment by frankluebeck** [comment]
Thank you for this example. The problem occurs in the LaTeX/PDF version of the manuals. 
Depending on loaded packages and used fonts LaTeX interprets `--` within a `\texttt` environment as ligature for a long dash (endash) and displays it as single dash.
With the change in commit 1d44fbb we now handle "-" like other LaTeX special characters. This avoids the mentioned problem.
