### ISSUE TITLE
Feature request: show style switch as a pop-over, instead of going to another page

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#7]
Right now, the style switcher changes to another URL, then let's you make some changes, and go back.

It would be much nicer if it was shown on a popover (using classic AJAX techniques, I guess). That way, changes could even be made live as the user changes options, giving an instant preview.

**Comment by frankluebeck** [comment]
I wanted to avoid any tricky javascript and don't like popovers (which I switch off in my browsers). 

It is more important that the pages look resonable without any javascript and graphical interface, say, in `w3m`.
