### ISSUE TITLE
Problem with `StringBibAsHTML` resp. `LaTeXToHTMLString` and MathJax

### ISSUE THREAD

**Issue by fingolfin** [frankluebeck/GAPDoc#71]
For the GAP website we show a bibliography also in HTML, using `LaTeXToHTMLString`. This worked fine so far, but now I've considered activating `MathJax` on those pages. That works well in some case, but not in others, mostly due to `LaTeXToHTMLString` stripping out all braces `{` and `}` quite eagerly. This turns e.g. `$M_{12}` into `$M_12$` which is fine when rendered as text (most mathematicians will happily read and understand it), but when passed through Mathjax it shows up as $M_12$ instead of $M_{12}$.  Worse with e.g. `$\Bbb{Z}$` (which renders as $\Bbb{Z}$) which gets turned into `$\BbbZ$` (rendering as $\BbbZ$).

I've locally hacked GAPDoc do resolve this by stripping braces only when they occur outside of math mode `$..$` sections, see PR #70.

However, that PR lacks test. Also, perhaps one may prefer the current output when not intending to use MathJax, so perhaps there should be a way to select between the two?

As such, I don't expect my PR to merged as-is, but perhaps it can be a starting point for a discussion how to deal with this.

CC @ThomasBreuer

**Comment by frankluebeck** [comment]
`MathJax` is already supported when the BibTeX entries are first translated to BibXMLext format.

I have uploaded an adjusted script for the conversion which uses this functionality, see [here](https://github.com/gap-system/GapWWW/pull/344).

**Comment by frankluebeck** [comment]
No longer needed.
