### ISSUE TITLE
Navigation in HTML version with Safari

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#8]
This happens with Safari browser on OS X: the block with subsections is not displayed properly.

* Broken (Safari, OS X)

![screen shot 2017-02-08 at 12 59 15](https://cloud.githubusercontent.com/assets/5751387/22738311/d4600262-edfe-11e6-88c9-31460eb6ef85.png)

* Works (Chrome, OS X)

![screen shot 2017-02-08 at 13 00 31](https://cloud.githubusercontent.com/assets/5751387/22738310/d45bb61c-edfe-11e6-9d11-b65d94353449.png)

**Comment by frankluebeck** [comment]
This looks like a specific Safari bug. 

Either use a better browser, or avoid the problem by clicking on [Style] and choosing `yes` on the point `Unfold subsections in menus only by mouse clicks:`.  (Needs to be done only once.)

**Comment by alex-konovalov** [comment]
Thanks. It works once in the _current_ session - after Safari is restarted, one should do it again, but at least this is a workaround.

**Comment by ChrisJefferson** [comment]
This bug also effects (for me at least) safari on the iPhone (where there are no alternative browsers) and Microsoft Edge.

One way of fixing it is to remove `overflow: auto` from `div.ChapSects`. That would I think only cause problems if that menu was very long. Of course, nothing is perfect in HTML-land.

**Comment by frankluebeck** [comment]
@alex-konovalov said:
> Thanks. It works once in the current session - after Safari is restarted, one should do it again, but at least this is a workaround.

Indeed, my description was not correct. You can change this permanently by adding `"toggless"` to the user preference `HTMLStyle` in your `gap.ini` file, e.g.,
```
SetUserPreference( "gapdoc", "HTMLStyle", [ "default", "ragged", "toggless" ] );
```

@ChrisJefferson said:
> One way of fixing it is to remove overflow: auto from div.ChapSects. That would I think only cause problems if that menu was very long. Of course, nothing is perfect in HTML-land.

Such long menus actually occur quite often (in particular on small screens with a limited number of rows). Leaving out 'overflow: auto' would be annoying.
