### ISSUE TITLE
References to obsolete `ReadTest`

### ISSUE THREAD

**Issue by alex-konovalov** [frankluebeck/GAPDoc#9]
When GAP is started with `-O` option, there are three syntax warnings displayed. This prevents us and prevents us from using `-O` option in continuos integration scripts:

```
Syntax warning: unbound global variable in /Users/alexk/gap4r8p6/pkg/GAPDoc-1.\
5.1/lib/BibXMLextTools.gi line 1336
  pos := PositionFirstComponent(strings, elt.attributes.key);
                               ^
Syntax warning: unbound global variable in /Users/alexk/gap4r8p6/pkg/GAPDoc-1.\
5.1/lib/Examples.gi line 208
  res := ReadTest(file);
                 ^
Syntax warning: unbound global variable in /Users/alexk/gap4r8p6/pkg/GAPDoc-1.\
5.1/lib/Examples.gi line 238
    ReadTest(inp);
            ^
```

The first of those is addressed by @fingolfin in #3. Addressing the other two requires changes in `lib/Examples.gi`, both in the code and the documentation.

**Comment by fingolfin** [comment]
Note that `ReadTest` only occures in two functions markes as "obsolete" by a comment, namely `TestExamplesString` and `ReadTestExamplesString`. I just checked, no package in the package distribution uses them. So it should be safe to just remove them from GAPDoc.

**Comment by fingolfin** [comment]
There is a third function marked as obsolete, `TestManualExamples`, but that one is still used by Hap, HomalgToCAS and happrime

**Comment by frankluebeck** [comment]
`TestManualExamples` uses the other mentioned functions. So, since they are still used, I should not remove them.

To avoid the problems when GAP is called with `-O` the obsolete functions are not defined in that case.

**Comment by alex-konovalov** [comment]
Ah, now I see that the code in the repository uses `MANEXreadobs` variable which checks whether `-O` has been used. I would really like a new release of GAPDoc with this change. Then we will finally be able to call GAP with `-O` on Travis. Otherwise, just today I've discovered that obsoletes crawled into the GAP library again:
```Syntax warning: Unbound global variable in /Users/alexk/GITREPS/gap/lib/grppcaut.gi:986
    stb:=NormedVectors(VectorSpace(f,bas));
                      ^
Syntax warning: Unbound global variable in /Users/alexk/GITREPS/gap/lib/grppcaut.gi:1308
   yet:=NormedVectors(field^n);
                     ^
Syntax warning: Unbound global variable in /Users/alexk/GITREPS/gap/lib/grppcaut.gi:1314
      i:=Set(List(NormedVectors(VectorSpace(field,i)),x->Position(yet,x)));
                               ^
Syntax warning: Unbound global variable in /Users/alexk/GITREPS/gap/lib/grppcaut.gi:1319
      i:=List(i,x->Set(List(NormedVectors(VectorSpace(field,x)),x->Position(yet,x))));
                                         ^
```
and also in some comments in the code.
